package eu.buney.kiche

expect class KicheConfig(version: UInt = QUICHE_PROTOCOL_VERSION) : AutoCloseable {
    fun loadCertChainFromPemFile(path: String)
    fun loadPrivKeyFromPemFile(path: String)
    fun loadVerifyLocationsFromFile(path: String)
    fun loadVerifyLocationsFromDirectory(path: String)
    fun verifyPeer(verify: Boolean)
    fun grease(enabled: Boolean)
    fun discoverPmtu(enabled: Boolean)
    fun logKeys()
    fun enableEarlyData()
    fun setApplicationProtos(protos: ByteArray)
    fun setMaxAmplificationFactor(factor: Long)
    fun setMaxIdleTimeout(millis: Long)
    fun setMaxRecvUdpPayloadSize(size: Long)
    fun setMaxSendUdpPayloadSize(size: Long)
    fun setInitialMaxData(v: Long)
    fun setInitialMaxStreamDataBidiLocal(v: Long)
    fun setInitialMaxStreamDataBidiRemote(v: Long)
    fun setInitialMaxStreamDataUni(v: Long)
    fun setInitialMaxStreamsBidi(v: Long)
    fun setInitialMaxStreamsUni(v: Long)
    fun setAckDelayExponent(v: Long)
    fun setMaxAckDelay(v: Long)
    fun setDisableActiveMigration(disabled: Boolean)
    fun setCcAlgorithm(algo: KicheCcAlgorithm)
    fun setInitialCongestionWindowPackets(packets: Long)
    fun enableHystart(enabled: Boolean)
    fun enablePacing(enabled: Boolean)
    fun setMaxPacingRate(v: Long)
    fun enableDgram(enabled: Boolean, recvQueueLen: Long, sendQueueLen: Long)
    fun setMaxConnectionWindow(v: Long)
    fun setMaxStreamWindow(v: Long)
    fun setActiveConnectionIdLimit(v: Long)
    fun setStatelessResetToken(token: ByteArray)
    fun setDisableDcidReuse(disabled: Boolean)
    fun setTicketKey(key: ByteArray)
    fun setEnableCubicIdleRestartFix(enabled: Boolean)
    override fun close()
}

const val QUICHE_PROTOCOL_VERSION: UInt = 0x00000001u
